services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventral-api
    restart: always
    env_file:
      - .env.prod
    expose:
      - "3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - npm_default

networks:
  npm_default:
    external: true
